// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-pcEQhPbGBu0gCiAEPAPN4x0DtfSTMMk',
    appId: '1:527015200496:web:1440c73128a2cfe91de435',
    messagingSenderId: '527015200496',
    projectId: 'fluttertest-6d55d',
    authDomain: 'fluttertest-6d55d.firebaseapp.com',
    storageBucket: 'fluttertest-6d55d.firebasestorage.app',
    measurementId: 'G-E1N73MJ34M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNSmJWtB9SKl7jwCT8RoVW9gZPoW_jNqM',
    appId: '1:527015200496:android:06a81f07b702283d1de435',
    messagingSenderId: '527015200496',
    projectId: 'fluttertest-6d55d',
    storageBucket: 'fluttertest-6d55d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKSum31EDg4v7AfIToo-N8yGnRZQ6P-TI',
    appId: '1:527015200496:ios:bbe28e2ca14615b11de435',
    messagingSenderId: '527015200496',
    projectId: 'fluttertest-6d55d',
    storageBucket: 'fluttertest-6d55d.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKSum31EDg4v7AfIToo-N8yGnRZQ6P-TI',
    appId: '1:527015200496:ios:bbe28e2ca14615b11de435',
    messagingSenderId: '527015200496',
    projectId: 'fluttertest-6d55d',
    storageBucket: 'fluttertest-6d55d.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-pcEQhPbGBu0gCiAEPAPN4x0DtfSTMMk',
    appId: '1:527015200496:web:9c0b5f7487457b021de435',
    messagingSenderId: '527015200496',
    projectId: 'fluttertest-6d55d',
    authDomain: 'fluttertest-6d55d.firebaseapp.com',
    storageBucket: 'fluttertest-6d55d.firebasestorage.app',
    measurementId: 'G-46S3F9GE0J',
  );
}
